name: Clean Disk with Disk Space Check

on:
  workflow_dispatch:
  workflow_run:
    workflows: clear disk  # 替换为你的工作流名称
    types:
      - completed

jobs:
  check-disk-space:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Display Disk Space Before Cleanup
      run: df -h

    - name: Clean Disk
      run: |
        # 进入根目录
        cd /

        # 删除不需要的文件和目录
        sudo rm -rf var/log/*  # 删除日志文件
        sudo rm -rf tmp/*      # 删除临时文件
        sudo apt clean         # 清理包缓存
        sudo apt autoremove    # 删除不再需要的依赖包

    - name: Display Disk Space After Cleanup
      run: df -h
